### PR TITLE
Update data with swapped barcodes from 3-11, 3-12, 6-7, 6-8

### PR DESCRIPTION
**Pull request by avahoffman**
Does a few things:

- Correct demux barcode `.txt` files
- Adds updated library statistics to `output/process_radtags-library_output.csv`
- Adds updated sample statistics to `output/process_radtags-sample_output.csv`
- Deletes ~~output/process_radtags-sample_output.csv~~ `output/process_radtags_out.csv` because it's redundant with `output/process_radtags-library_output.csv`

Also discovered that samples were missing from `output/process_radtags-sample_output.csv`. Went back into the logs and added these in here.

Ready now to determine outliers :)

### CODE REVIEW

**Comment by Jennycocciardi** [comment]
Awesome! Looks great : ) I'll get to working on the outliers. 

My only comment is that we should keep the `output/process_radtags-sample_output.csv`. It may look redundant to the `output/process_radtags-library_output.csv`, but it has different information (unless I'm thinking of something else). This is the file that we use to ID the outliers. The `sample_output` contains the data for each individual sample, while the `library_output` contains the data aggregated by sublibrary (so the overall library stats). 

Let me also add a README file to this folder so we can have everything explained... can we talk about this and you can show me how to do that? Thank you!!!

**Comment by avahoffman** [comment]
apologies for the typo! output/process_radtags_out.csv because it's redundant with output/process_radtags-library_output.csv

**Comment by avahoffman** [comment]
@Jennycocciardi a few new things here:

- Added a script to filter. Best not to do this in excel 🙂 
- Created two new files, 
     - `process_radtags-kept_samples.csv` (contains good samples)
     - `process_radtags-discarded_samples.csv` (contains low cov samples)
- Deleted `process_radtags-outliers_and_samples_removed.csv` - this is now outdated, no?

**Comment by Jennycocciardi** [comment]
This is great! Thank you : )

**Review by Jennycocciardi — APPROVED** [review]

**Pull request merged**
